### ISSUE TITLE
Advice request: creating an equivalent to rk1.rk05

### ISSUE THREAD

**Issue by mwenge** [tschak909/atari-coin-op-assembler#1]
Hi there,

Very pleased to find your pages https://github.com/tschak909/atari-coin-op-assembler/tree/main/coin-op and https://github.com/tschak909/atari-coin-op-assembler/tree/main/coin-op detailing how to boot up a PDP-11 and assemble a game. I've been able to recreate the steps so am delighted at the unexpected progress!

I'd like to do the same with https://github.com/historicalsource/tempest and realize I need some way to generate a rk1.rk05 image file from the sources. Any suggestions how to go about this (on linux)? I haven't been able to find anything so far!

**Comment by tschak909** [comment]
cut and paste the source into KED. :)
-Thom

**Comment by mwenge** [comment]
Oh joy! :)

**Comment by mwenge** [comment]
I ended up [creating a script to generate the disk image for me](https://github.com/mwenge/tempest/blob/master/notebooks/Create%20RK05%20Disk%20Cartridge%20File%20Image%20From%20Tempest%20Sources.ipynb). I also have [one for extracting files from a disk](https://github.com/mwenge/tempest/blob/master/notebooks/Extract%20Object%20Files%20from%20Tempest%20RK05%20Disk%20after%20Assembling%20and%20Linking.ipynb).
